CREATE TABLE booklists (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  list_name VARCHAR(50) NOT NULL,
  list_description VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  UNIQUE KEY uq_listname_per_user (user_id, list_name),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);