CREATE TABLE reviews (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  book_id VARCHAR(32) NOT NULL,
  user_id BIGINT NOT NULL,
  content VARCHAR(255),
  rate INT NOT NULL CHECK (rate BETWEEN 0 AND 10),
  favorite BOOLEAN NOT NULL DEFAULT FALSE,
  reviewed_at DATE DEFAULT CURRENT_DATE,

  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);